# Mode: just Pbft replication

mode:
  cc: none # concurrency control
  ab: fpga_raft # atomic broadcast
  read_only: occ
  batch: false
  retry: 20
  ongoing: 1 # per client

# Sites: 1 server, 4 replicas

site:
  server:
    - ["s101:8101", "s102:8102", "s103:8103", "s104:8104"]

process:
  s101: localhost
  s102: localhost
  s103: localhost
  s104: localhost

host:
  localhost: 127.0.0.1

keys:
  s101:
    privkey: "keys/s101_priv.pem"
    pubkey: "keys/s101_pub.pem"
  s102:
    privkey: "keys/s102_priv.pem"
    pubkey: "keys/s102_pub.pem"
  s103:
    privkey: "keys/s103_priv.pem"
    pubkey: "keys/s103_pub.pem"
  s104:
    privkey: "keys/s104_priv.pem"
    pubkey: "keys/s104_pub.pem"
